import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Furrier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/logo.png" />
      </Head>
    
      <Navbar />
        <div className="  ">
        <h1 className="px-20 font-sans text-3xl font-bold text-gray-600">Home</h1>
        </div>
    </div>
  )
}
