import Head from 'next/head'
import Navbar from '../components/Navbar'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Furrier</title>
        <meta name="description" content="Generated by create next app" />
        {/*<link rel="icon" href="../public/logo.png" />*/}
      </Head>
    
      <Navbar />

      {/* Head */}
      <div className="mt-7 bg-slate-800 h-screen w-full bg-[url('../public/header.jpeg')] bg-cover bg-blend-overlay">
      <h1 className="text-9xl text-white w-1/2 font-bold mx-auto py-52">WELCOME TO FURRIER</h1>
      {/*<Image
      src="/header.jpeg"
      alt="Picture of the author"
      width="100%" height="55%" layout="responsive" objectFit="fill"
      />*/}
      </div>

      {/* About Us */}
      <div className="px-20 md:pl-40 py-52 h-screen">
        <h1 className="title font-sans text-xl md:text-3xl font-medium text-cyan-600 mb-10">About Us</h1>
        <div>
        <div className=" w-4/6 ">
        <p>Furrier is an Animal Welfare platform and an Information Hub for current and prospective pet owners, which aims to assist the owners in taking better care for their pets, by connecting them with essential facilities/services and by providing services like health/medication monitoring, diet plans for pets etc.</p>
        <br />
        <p>Furthermore, we also aim to Promote and assist adoption of animals and contribute towards other animal welfare programs as well as create awareness regarding prominent issues of Animal Welfare, and propose possible solutions</p>
        </div>    
        </div>
        <button className="my-12 border-r-2 border-b-2 border-l-2 border-gray-200 bg-white shadow-md rounded-r-full rounded-l-full p-4 font-bold text-cyan-600 text-md hover:shadow-lg w-full md:w-40">Know More</button>
      </div>

      {/* Services */}
      <hr/>
      <div className="px-20 md:pl-40 py-72 h-screen bg-gray-100">
        <h1 className="title font-sans text-xl md:text-3xl font-medium text-cyan-600 mb-10">Services</h1>
        <div>
        <p className=" w-1/2 ">We provide various services that are important for your pet. Check out our services and provide your pet with the best facilities available in the town</p>  
        </div>
        <button className="my-12 border-r-2 border-b-2 border-l-2 border-gray-200 bg-white shadow-md rounded-r-full rounded-l-full p-4 font-bold text-cyan-600 text-md hover:shadow-lg w-full md:w-40">View Page</button>
      </div>

      {/* Adoption */}
      <hr/>
      <div className="px-20 md:pl-40 py-72 h-screen">
        <h1 className="title font-sans text-xl md:text-3xl font-medium text-cyan-600 mb-10">Adoption</h1>
        <div>
        <p className=" w-1/2 ">Check out the necessary guidelines required to adopt a pet to prevent yourself from any unknown legal troubles.

Also, check out the 'Available Pets' section to know your options.  </p>  
        </div>
        <button className="my-12 border-r-2 border-b-2 border-l-2 border-gray-200 bg-white shadow-md rounded-r-full rounded-l-full p-4 font-bold text-cyan-600 text-md hover:shadow-lg w-full md:w-40">View Page</button>
      </div>

      {/* Help Desk - FAQs */}
      <hr/>
      <div className="px-20 md:pl-40 py-72 h-screen bg-gray-100">
        <h1 className="title font-sans text-xl md:text-3xl font-medium text-cyan-600 mb-10">Help Desk - FAQs</h1>
        <div>
        <p className=" w-1/2 ">Check out the FAQs in the Help Desk tab. Feel free to contact us in case of any further queries.</p>  
        </div>
        <button className="my-12 border-r-2 border-b-2 border-l-2 border-gray-200 bg-white shadow-md rounded-r-full rounded-l-full p-4 font-bold text-cyan-600 text-md hover:shadow-lg w-full md:w-40">View Page</button>
      </div>

    </div>
  )
}
